### ISSUE TITLE
Progress bar on large collection always shows total 1.34 TB

### ISSUE THREAD

**Issue by jefft0** [ipfs-filestore/go-ipfs#8] opened 2016-06-08 07:35 UTC
A UI issue. I built the branch issue-6 on Windows 8.1 and did `ipfs filestore add -r c:\public\cameras` on a video collection of about 12 TB. The progress bar only counted 1.32 TB. Indeed, after about a day, the progress bar shows progress over 100%:

```
 1.45 TB / 1.34 TB [==============================] 108.61% -59m6s
```

So I think it is processing all the files, but something is wrong with how it makes the initial total. I tried it on other large collections of different sizes over 2 TB and each time the total shows 1.34 TB.

**Comment by kevina** [comment] 2016-06-08 18:28
@jefft0 Could you try a normal add to see what the progress bar tells you?  You can cancel it shortly after it starts.

**Comment by jefft0** [comment] 2016-06-08 19:19
Normal `ipfs add` also shows a weird total. This time when I run both `ipfs add` and `ipfs filestore add` it shows:

```
 213.24 MB / 142.44 MB [================] 149.71% -12s
```

Now the total is "stuck" at 142.44 MB which is suspicious because that the size of the previous file that I added. Even weirder is that inbetween tests I've been deleting the .ipfs folder and doing a new `ipfs init`. So I don't know where it could be saving this stuck value.

**Comment by kevina** [comment] 2016-06-08 21:27
Thanks.

I am fairly certain this is not something caused by the filestore code, although I am not willing to completely rule that out just yet.

Have you noticed this problem before?

**Comment by jefft0** [comment] 2016-06-09 09:02
You're right. I tried the master branch from the main go-ipfs repository. It also shows "?" for the total, even on a small collection sometimes. So, we can close this issue. I have trouble reproducing the problem. If I have time I'll look into the go code to see if I can find the problem and open an issue on the main repo.

**Comment by kevina** [comment] 2016-06-09 18:46
So just to be sure.  In addition to a '?' for the total you are also seeing incorrect totals?

**Comment by jefft0** [comment] 2016-06-09 18:49
No. Sometimes it shows "?" and sometimes an incorrect total (apparently from a previous add). The last few times I tried, it just showed "?", even on collections that were pretty small (a few gigabytes). For smaller collections of course, sometimes it shows the correct total. I have trouble reproducing it. Since it is "only" a UI issue and maybe Windows-specific it's not a high priority for me.

**Comment by kevina** [comment] 2016-06-09 19:19
No problem.  This is not a high priority for me also, now that I am sure I did not brake anything.  Closing.

**Closed as completed by kevina** 2016-06-09 19:19 UTC
